SELECT MUNICIPIO_RES, COUNT(CLASIFICACION_FINAL) AS TOTAL_CASOS 
FROM Registros
WHERE ENTIDAD_UM = 26 
AND MUNICIPIO_RES BETWEEN 1 AND 72
AND CLASIFICACION_FINAL IN(1,2,3,4,5) 
GROUP BY MUNICIPIO_RES
ORDER BY COUNT(CLASIFICACION_FINAL) DESC;
